### ISSUE TITLE
[SUGGESTION] Create a website to administrate everything

### ISSUE THREAD

**Issue by oskariin7** [FerranMarin/axie-scholar-utilities#27]
In order to make this amazing code more usable, I suggest to create a website in order to populate or modify the payments.json file, to claim just by clicking a button or the execute the payout on the same way.

What do you think?

**Comment by FerranMarin** [comment]
It is a good idea, but, if you go to https://axie.management/tracker/payments and use their tracker, you can get an export in the form of the payments.json.
My plan is to also create a new input in form of percents and not full numbers so people won't need to re-do their files everytime and won't leave SLP in the accounts just due to timing between creating payments.json and claiming time.

So, because of that, I will be closing this issue. If you do not agree, please re-open it or open a new one :)

**Comment by oskariin7** [comment]
What I thought was to create a simple web just in other to execute the claim and the payout actions. I didn't know that in that website we had our payments.json populated already, but for claim and payout actions it could be good. Anyway, maybe is too much effort for something that just requires the execution of an alias... 

I like a lot the idea of the percents! Waiting for that functionality :)

Thanks for your answer.

**Comment by FerranMarin** [comment]
To execute the commands you need to run them in your computer. I am working on a Desktop app that will do the same, but it's taking a bit of extra time as it's something I've never done before.

**Comment by oskariin7** [comment]
That's really nice! I don't know a lot about that but I can program in python. Let me know if you need help for anything :)

Really nice work FerranMarin!
